// 다례(茶禮) 취향 큐레이터 데이터셋 — tea-mvp-reference.html에서 그대로 이식
const TASTE_OPTS = [
  { id: "astringent", label: "떫은맛" },
  { id: "sweet", label: "단맛" },
  { id: "savory", label: "구수함" },
  { id: "tangy", label: "산미·상큼함" },
  { id: "floral", label: "꽃·향긋함" },
];

const CAFFEINE_OPTS = [
  { id: "need", label: "카페인 필요해요" },
  { id: "free", label: "무카페인 선호" },
  { id: "any", label: "상관없어요" },
];

const PURPOSE_OPTS = [
  { id: "relax", label: "이완·휴식" },
  { id: "focus", label: "집중·각성" },
  { id: "digest", label: "소화·속편함" },
  { id: "health", label: "건강관리·다이어트" },
  { id: "gift", label: "선물·특별한 날" },
];

// images: 위키미디어 커먼즈(CC 라이선스) 파일명. commonsUrl()로 실제 URL을 만든다.
// options: 용량별 판매 단가. 첫 항목이 기본 선택이자 목록의 "~원부터" 기준가.
const TEAS = [
  { id: "hadong-ujeon", name: "하동 우전 녹차", origin: "국내 · 경남 하동", category: "녹차",
    images: ["Dried_jakseol_green_tea_leaves.jpg", "Drying_jakseol_green_tea_leaves.jpg"],
    taste: ["savory", "sweet"], caffeine: "need", purpose: ["focus", "gift"],
    effect: "떫지 않고 감칠맛이 강한 첫물차. 카테킨이 풍부해 각성·항산화에 도움.",
    brew: "70°C 물, 찻잎 3g, 1분 30초",
    options: [{ weight: "50g", price: 25000 }, { weight: "100g", price: 40000 }],
    story: "곡우 전 딴 첫잎만 쓰는 하동의 대표 전통 녹차. 국내 녹차 산지 중 재배 역사가 가장 깁니다." },
  { id: "boseong-sejak", name: "보성 세작 녹차", origin: "국내 · 전남 보성", category: "녹차",
    images: ["Boseong_banner_Green_Tea_Plantation.jpg", "Green_tea_leaves.jpg"],
    taste: ["astringent", "savory"], caffeine: "need", purpose: ["focus"],
    effect: "우전보다 진한 떫은맛과 개운한 뒷맛. 식사 후 입가심에 좋음.",
    brew: "75°C 물, 찻잎 3g, 1분",
    options: [{ weight: "100g", price: 15000 }, { weight: "200g", price: 25000 }],
    story: "보성 다원의 계단식 차밭에서 자란 잎으로 만든, 가장 대중적인 국산 녹차." },
  { id: "hadong-hwangcha", name: "하동 황차", origin: "국내 · 경남 하동", category: "발효차",
    images: ["Hwangcha.jpg", "Korean tea hwangcha Naju South Korea 2015-01-17(3).jpg"],
    taste: ["sweet", "savory"], caffeine: "need", purpose: ["digest", "relax"],
    effect: "약발효로 떫은맛을 낮추고 단맛을 살린 차. 위에 부담이 적어 공복에도 무난.",
    brew: "85°C 물, 찻잎 3g, 2분",
    options: [{ weight: "50g", price: 20000 }, { weight: "100g", price: 30000 }],
    story: "녹차보다 산화를 더 진행시켜 구수함을 끌어올린 한국 고유의 발효 방식." },
  { id: "yunnan-puer", name: "윈난 보이차(숙차)", origin: "해외 · 중국 윈난성", category: "발효차",
    images: ["Pu-erh_tea.JPG", "Pu-erh_tea_back.JPG"],
    taste: ["savory"], caffeine: "need", purpose: ["digest", "health"],
    effect: "후발효차 특유의 흙내와 구수함. 기름진 음식 후 소화를 돕는다고 알려짐.",
    brew: "95°C 물, 찻잎 5g, 세차 후 20~30초씩 여러 번",
    options: [{ weight: "병차 100g", price: 30000 }, { weight: "병차 357g", price: 80000 }],
    story: "윈난 대엽종을 눌러 저장·후발효시킨 차. 오래 묵힐수록 맛이 부드러워집니다." },
  { id: "taiwan-oolong", name: "대만 동방미인 우롱차", origin: "해외 · 대만 신주", category: "우롱차",
    images: ["Oolong_tea_leaf.jpg", "HGY_Oolong_tea_leaf_close.jpg"],
    taste: ["floral", "sweet"], caffeine: "any", purpose: ["gift", "relax"],
    effect: "진딧물이 문 잎으로 만들어 과일·꿀 향이 강한 고급 반발효차.",
    brew: "90°C 물, 찻잎 4g, 1분",
    options: [{ weight: "50g", price: 40000 }, { weight: "100g", price: 70000 }],
    story: "벌레가 갉아먹은 잎이 오히려 특유의 향을 만든다는, 우연에서 시작된 명차." },
  { id: "darjeeling", name: "다르질링 홍차(퍼스트 플러시)", origin: "해외 · 인도 다르질링", category: "홍차",
    images: ["Darjeeling-tea-first-flush-in-cup.jpg", "Darjeeling, India, Darjeeling tea.jpg"],
    taste: ["tangy", "astringent"], caffeine: "need", purpose: ["focus"],
    effect: "머스캣 포도 향과 산뜻한 산미. '홍차의 샴페인'으로 불림.",
    brew: "90°C 물, 찻잎 3g, 3분",
    options: [{ weight: "50g", price: 20000 }, { weight: "100g", price: 40000 }],
    story: "봄 첫 수확분만 이렇게 불리며, 세계 홍차 경매가에서 가장 높은 값에 거래됩니다." },
  { id: "breakfast-blend", name: "잉글리시 브렉퍼스트 블렌드", origin: "해외 · 인도·스리랑카 블렌드", category: "홍차",
    images: ["Cup_of_black_tea.JPG", "A_cup_of_Tea.jpg"],
    taste: ["astringent", "sweet"], caffeine: "need", purpose: ["focus"],
    effect: "진하고 묵직한 바디감. 우유·설탕과 잘 어울려 아침 각성용으로 적합.",
    brew: "100°C 물, 찻잎 3g, 3~4분",
    options: [{ weight: "100g", price: 12000 }, { weight: "200g", price: 20000 }],
    story: "아삼과 실론 찻잎을 배합해 진한 맛을 표준화한, 가장 널리 소비되는 홍차 블렌드." },
  { id: "chrysanthemum", name: "국화차", origin: "국내 · 전북 정읍", category: "화차",
    images: ["Korean_chrysanthemum_tea-Gukhwacha-01.jpg", "Chrysanthemum_tea.JPG"],
    taste: ["floral", "sweet"], caffeine: "free", purpose: ["relax", "health"],
    effect: "은은한 단향과 무카페인. 눈의 피로와 열감을 내리는 데 전통적으로 쓰임.",
    brew: "90°C 물, 꽃 4~5송이, 3분",
    options: [{ weight: "30g", price: 15000 }, { weight: "60g", price: 25000 }],
    story: "조선시대부터 선비들이 즐겨 마신 대표적인 화차로, 국화 향이 그대로 우러납니다." },
  { id: "yuja", name: "유자차", origin: "국내 · 전남 고흥", category: "과일청차",
    images: ["Korean tea-Yujacha-02.jpg", "Korean tea-Yujacha-05.jpg"],
    taste: ["sweet", "tangy"], caffeine: "free", purpose: ["health", "gift"],
    effect: "비타민C가 풍부한 유자청을 끓는 물에 타 마시는 형태. 환절기 목 관리용으로 인기.",
    brew: "뜨거운 물 200ml + 유자청 2스푼",
    options: [{ weight: "500g", price: 12000 }, { weight: "1kg", price: 18000 }],
    story: "겨울 선물세트로 가장 많이 팔리는 국내 전통 음청류 중 하나." },
  { id: "chamomile", name: "캐모마일", origin: "해외 · 이집트", category: "허브차",
    images: ["Loose_chamomile_tea.jpg"],
    taste: ["floral", "sweet"], caffeine: "free", purpose: ["relax"],
    effect: "사과 같은 은은한 단향. 잠들기 전 마시는 허브차로 가장 널리 알려짐.",
    brew: "95°C 물, 꽃 2g, 4분",
    options: [{ weight: "20티백", price: 10000 }, { weight: "40티백", price: 18000 }],
    story: "유럽에서 수백 년간 '잠들기 전 한 잔'으로 자리잡은 대표 허브차." },
  { id: "peppermint", name: "페퍼민트", origin: "해외 · 모로코", category: "허브차",
    images: ["Peppermint-tea_hg.jpg", "Tunisia-09-mint tea (6493856887).jpg"],
    taste: ["tangy"], caffeine: "free", purpose: ["digest"],
    effect: "시원한 멘톨 향이 소화를 돕고 속을 편하게 함. 식후 차로 적합.",
    brew: "95°C 물, 잎 2g, 3분",
    options: [{ weight: "20티백", price: 9000 }, { weight: "40티백", price: 15000 }],
    story: "모로코 민트티 문화의 기본이 되는 허브로, 전 세계 식후 차 문화의 스테디셀러." },
  { id: "rooibos", name: "루이보스", origin: "해외 · 남아프리카공화국", category: "허브차",
    images: ["Rooibos_tea_in_a_glass_with_dry_rooibos.jpg", "Rooibos_tea_2.jpg"],
    taste: ["sweet", "savory"], caffeine: "free", purpose: ["health"],
    effect: "카페인 없이도 은은한 단맛. 항산화 성분이 풍부해 다이어트·컨디션 관리용으로 인기.",
    brew: "100°C 물, 찻잎 3g, 5분(오래 우려도 안 떫음)",
    options: [{ weight: "100g", price: 13000 }, { weight: "200g", price: 20000 }],
    story: "남아공 세더버그 지역에서만 자라는 관목으로, 오래 끓여도 떫지 않은 몇 안 되는 차." },
  { id: "gyeolmyeongja", name: "결명자차", origin: "국내 · 충남 태안", category: "허브차",
    images: [],
    taste: ["savory"], caffeine: "free", purpose: ["health", "relax"],
    effect: "구수한 볶은 맛. 예로부터 눈 건강과 이뇨 작용에 좋다고 알려진 전통 약차.",
    brew: "물 1L에 결명자 15g, 10분 끓이기",
    options: [{ weight: "200g", price: 8000 }, { weight: "500g", price: 13000 }],
    story: "보리차만큼 대중적이었던 국내 가정 상비차로, 최근 재조명되는 전통 약차 중 하나." },
  { id: "jasmine", name: "자스민 화차", origin: "국내 재가공 · 중국 푸젠성 원료", category: "화차",
    images: ["Jasmine_tea.jpg", "Jasmine_Flower_Tea.jpg"],
    taste: ["floral"], caffeine: "any", purpose: ["relax", "gift"],
    effect: "녹차에 자스민 꽃향을 입힌 차. 가볍고 산뜻해 식사 자리에 두루 잘 어울림.",
    brew: "85°C 물, 찻잎 3g, 2분",
    options: [{ weight: "50g", price: 15000 }, { weight: "100g", price: 25000 }],
    story: "녹차 위에 자스민 꽃을 여러 번 덮어 향을 입히는 전통 훈화 공법으로 만들어집니다." },
];

// 커뮤니티 피드 — 다례 팀이 직접 작성하는 콘텐츠 (팀 계정 발행 전 초안.
// 좋아요/댓글/스크랩 수는 배포 시 0에서 시작하며 가짜 반응은 넣지 않는다)
const FEED_POSTS = [
  { id: "post-caffeine-guide", category: "녹차", date: "2026.09.05", readMin: 4,
    image: "Dried_jakseol_green_tea_leaves.jpg",
    title: "카페인 예민한데 녹차 좋아한다면? 우전과 세작의 차이",
    summary: "같은 녹차인데 왜 어떤 건 잠이 안 오고 어떤 건 괜찮을까요. 첫물차와 늦물차의 카테킨 함량 차이부터 우리는 물 온도까지, 카페인 부담을 줄이는 우리기 팁을 정리했습니다." },
  { id: "post-puer-myth", category: "발효차", date: "2026.09.03", readMin: 6,
    image: "Pu-erh_tea.JPG",
    title: "보이차는 다 똑같지 않습니다 — 생차 vs 숙차 완전 정리",
    summary: "보이차 하나로 뭉뚱그려 부르지만 발효 방식에 따라 맛과 효능이 완전히 다릅니다. 처음 보이차를 접하는 분들이 가장 많이 헷갈리는 지점을 짧게 짚어드려요." },
  { id: "post-herbal-sleep", category: "허브차", date: "2026.09.01", readMin: 3,
    image: "Loose_chamomile_tea.jpg",
    title: "잠들기 전 한 잔, 캐모마일 말고도 있습니다",
    summary: "캐모마일이 대표적이지만 취향에 안 맞을 수도 있어요. 무카페인이면서 이완에 도움을 주는 허브차 3종을 향과 맛 기준으로 비교했습니다." },
  { id: "post-darjeeling-flush", category: "홍차", date: "2026.08.28", readMin: 5,
    image: "Darjeeling-tea-first-flush-in-cup.jpg",
    title: "퍼스트 플러시가 비싼 이유, 한 번은 마셔볼 가치가 있을까",
    summary: "봄 첫 수확분이라는 이유만으로 가격이 두 배가 됩니다. 세컨드 플러시와 나란히 우려 마셔보고 향·바디감·가격을 기준으로 솔직하게 정리했습니다." },
  { id: "post-yuja-winter", category: "과일청차", date: "2026.08.25", readMin: 3,
    image: "Korean tea-Yujacha-02.jpg",
    title: "환절기 목 관리, 유자차는 몇 스푼이 적당할까",
    summary: "유자청은 설탕 비율이 높아 무작정 진하게 타면 단맛만 남습니다. 물 온도와 스푼 수를 바꿔가며 가장 균형 잡힌 비율을 찾아봤습니다." },
  { id: "post-flower-tea", category: "화차", date: "2026.08.21", readMin: 4,
    image: "Jasmine_Flower_Tea.jpg",
    title: "향으로 마시는 차, 화차 입문 가이드",
    summary: "자스민·국화처럼 꽃향을 입힌 차는 첫인상이 강해 호불호가 갈립니다. 처음 마신다면 어떤 순서로 접근하면 좋은지 정리했습니다." },
  { id: "post-oolong-range", category: "우롱차", date: "2026.08.18", readMin: 5,
    image: "Oolong_tea_leaf.jpg",
    title: "우롱차는 녹차와 홍차 사이 어디쯤에 있을까",
    summary: "산화도에 따라 같은 우롱차도 녹차에 가깝기도, 홍차에 가깝기도 합니다. 산화도별로 맛이 어떻게 달라지는지 지도처럼 그려봤습니다." },
  { id: "post-boseong-field", category: "녹차", date: "2026.08.14", readMin: 7,
    image: "Boseong_banner_Green_Tea_Plantation.jpg",
    title: "보성 다원에 다녀왔습니다 — 계단식 차밭이 만드는 맛",
    summary: "같은 품종이라도 경사와 해무에 따라 잎이 달라집니다. 산지에서 직접 보고 들은 재배 방식이 우리 잔에 어떻게 도착하는지 이야기합니다." },
];
