// 다례(茶禮) 취향 큐레이터 데이터셋 — tea-mvp-reference.html에서 그대로 이식
const TASTE_OPTS = [
  { id: "astringent", label: "떫은맛" },
  { id: "sweet", label: "단맛" },
  { id: "savory", label: "구수함" },
  { id: "tangy", label: "산미·상큼함" },
  { id: "floral", label: "꽃·향긋함" },
];

const CAFFEINE_OPTS = [
  { id: "need", label: "카페인 필요해요" },
  { id: "free", label: "무카페인 선호" },
  { id: "any", label: "상관없어요" },
];

const PURPOSE_OPTS = [
  { id: "relax", label: "이완·휴식" },
  { id: "focus", label: "집중·각성" },
  { id: "digest", label: "소화·속편함" },
  { id: "health", label: "건강관리·다이어트" },
  { id: "gift", label: "선물·특별한 날" },
];

// 바디감 — 입안에 남는 무게감
const BODY_OPTS = [
  { id: "light", label: "가볍고 산뜻하게" },
  { id: "medium", label: "중간 정도" },
  { id: "full", label: "진하고 묵직하게" },
  { id: "any", label: "상관없어요" },
];

// 향의 세기
const AROMA_OPTS = [
  { id: "subtle", label: "은은하게" },
  { id: "clear", label: "뚜렷하게" },
  { id: "bold", label: "확실히 강하게" },
  { id: "any", label: "상관없어요" },
];

// 주로 마시는 시간대
const TIME_OPTS = [
  { id: "morning", label: "아침" },
  { id: "afternoon", label: "낮·오후" },
  { id: "evening", label: "저녁·자기 전" },
  { id: "any", label: "때를 가리지 않아요" },
];

// 우리는 데 들이는 정성
const EFFORT_OPTS = [
  { id: "easy", label: "간편하게 (티백·타 먹기)" },
  { id: "standard", label: "찻잎 우려서" },
  { id: "ritual", label: "다구 갖춰 천천히" },
  { id: "any", label: "상관없어요" },
];

// 차 경험 — 입문자에게 강한 차를 밀지 않기 위한 기준
const LEVEL_OPTS = [
  { id: "beginner", label: "차는 거의 처음이에요" },
  { id: "intermediate", label: "몇 가지 마셔봤어요" },
  { id: "advanced", label: "꽤 익숙해요" },
];

// images: 위키미디어 커먼즈(CC 라이선스) 파일명. commonsUrl()로 실제 URL을 만든다.
// options: 용량별 판매 단가. 첫 항목이 기본 선택이자 목록의 "~원부터" 기준가.
const TEAS = [
  { id: "hadong-ujeon", name: "하동 우전 녹차", origin: "국내 · 경남 하동", group: "domestic", category: "녹차",
    images: ["Dried_jakseol_green_tea_leaves.jpg", "Drying_jakseol_green_tea_leaves.jpg"],
    taste: ["savory", "sweet"], caffeine: "need", purpose: ["focus", "gift"],
    body: "light", aroma: "subtle", time: ["morning", "afternoon"], effort: "standard", level: "intermediate",
    effect: "떫지 않고 감칠맛이 강한 첫물차. 카테킨이 풍부해 각성·항산화에 도움.",
    brew: "70°C 물, 찻잎 3g, 1분 30초",
    options: [{ weight: "50g", price: 25000 }, { weight: "100g", price: 40000 }],
    story: "곡우 전 딴 첫잎만 쓰는 하동의 대표 전통 녹차. 국내 녹차 산지 중 재배 역사가 가장 깁니다." },
  { id: "boseong-sejak", name: "보성 세작 녹차", origin: "국내 · 전남 보성", group: "domestic", category: "녹차",
    images: ["Boseong_banner_Green_Tea_Plantation.jpg", "Green_tea_leaves.jpg"],
    taste: ["astringent", "savory"], caffeine: "need", purpose: ["focus"],
    body: "medium", aroma: "clear", time: ["afternoon"], effort: "standard", level: "beginner",
    effect: "우전보다 진한 떫은맛과 개운한 뒷맛. 식사 후 입가심에 좋음.",
    brew: "75°C 물, 찻잎 3g, 1분",
    options: [{ weight: "100g", price: 15000 }, { weight: "200g", price: 25000 }],
    story: "보성 다원의 계단식 차밭에서 자란 잎으로 만든, 가장 대중적인 국산 녹차." },
  { id: "hadong-hwangcha", name: "하동 황차", origin: "국내 · 경남 하동", group: "domestic", category: "발효차",
    images: ["Hwangcha.jpg", "Korean tea hwangcha Naju South Korea 2015-01-17(3).jpg"],
    taste: ["sweet", "savory"], caffeine: "need", purpose: ["digest", "relax"],
    body: "medium", aroma: "clear", time: ["afternoon", "evening"], effort: "standard", level: "intermediate",
    effect: "약발효로 떫은맛을 낮추고 단맛을 살린 차. 위에 부담이 적어 공복에도 무난.",
    brew: "85°C 물, 찻잎 3g, 2분",
    options: [{ weight: "50g", price: 20000 }, { weight: "100g", price: 30000 }],
    story: "녹차보다 산화를 더 진행시켜 구수함을 끌어올린 한국 고유의 발효 방식." },
  { id: "yunnan-puer", name: "윈난 보이차(숙차)", origin: "해외 · 중국 윈난성", group: "overseas", category: "발효차",
    images: ["Pu-erh_tea.JPG", "Pu-erh_tea_back.JPG"],
    taste: ["savory"], caffeine: "need", purpose: ["digest", "health"],
    body: "full", aroma: "bold", time: ["afternoon", "evening"], effort: "ritual", level: "advanced",
    effect: "후발효차 특유의 흙내와 구수함. 기름진 음식 후 소화를 돕는다고 알려짐.",
    brew: "95°C 물, 찻잎 5g, 세차 후 20~30초씩 여러 번",
    options: [{ weight: "병차 100g", price: 30000 }, { weight: "병차 357g", price: 80000 }],
    story: "윈난 대엽종을 눌러 저장·후발효시킨 차. 오래 묵힐수록 맛이 부드러워집니다." },
  { id: "taiwan-oolong", name: "대만 동방미인 우롱차", origin: "해외 · 대만 신주", group: "overseas", category: "우롱차",
    images: ["Oolong_tea_leaf.jpg", "HGY_Oolong_tea_leaf_close.jpg"],
    taste: ["floral", "sweet"], caffeine: "any", purpose: ["gift", "relax"],
    body: "medium", aroma: "bold", time: ["afternoon"], effort: "standard", level: "intermediate",
    effect: "진딧물이 문 잎으로 만들어 과일·꿀 향이 강한 고급 반발효차.",
    brew: "90°C 물, 찻잎 4g, 1분",
    options: [{ weight: "50g", price: 40000 }, { weight: "100g", price: 70000 }],
    story: "벌레가 갉아먹은 잎이 오히려 특유의 향을 만든다는, 우연에서 시작된 명차." },
  { id: "darjeeling", name: "다르질링 홍차(퍼스트 플러시)", origin: "해외 · 인도 다르질링", group: "overseas", category: "홍차",
    images: ["Darjeeling-tea-first-flush-in-cup.jpg", "Darjeeling, India, Darjeeling tea.jpg"],
    taste: ["tangy", "astringent"], caffeine: "need", purpose: ["focus"],
    body: "light", aroma: "bold", time: ["morning", "afternoon"], effort: "standard", level: "intermediate",
    effect: "머스캣 포도 향과 산뜻한 산미. '홍차의 샴페인'으로 불림.",
    brew: "90°C 물, 찻잎 3g, 3분",
    options: [{ weight: "50g", price: 20000 }, { weight: "100g", price: 40000 }],
    story: "봄 첫 수확분만 이렇게 불리며, 세계 홍차 경매가에서 가장 높은 값에 거래됩니다." },
  { id: "breakfast-blend", name: "잉글리시 브렉퍼스트 블렌드", origin: "해외 · 인도·스리랑카 블렌드", group: "overseas", category: "홍차",
    images: ["Cup_of_black_tea.JPG", "A_cup_of_Tea.jpg"],
    taste: ["astringent", "sweet"], caffeine: "need", purpose: ["focus"],
    body: "full", aroma: "clear", time: ["morning"], effort: "standard", level: "beginner",
    effect: "진하고 묵직한 바디감. 우유·설탕과 잘 어울려 아침 각성용으로 적합.",
    brew: "100°C 물, 찻잎 3g, 3~4분",
    options: [{ weight: "100g", price: 12000 }, { weight: "200g", price: 20000 }],
    story: "아삼과 실론 찻잎을 배합해 진한 맛을 표준화한, 가장 널리 소비되는 홍차 블렌드." },
  { id: "chrysanthemum", name: "국화차", origin: "국내 · 전북 정읍", group: "domestic", category: "화차",
    images: ["Korean_chrysanthemum_tea-Gukhwacha-01.jpg", "Chrysanthemum_tea.JPG"],
    taste: ["floral", "sweet"], caffeine: "free", purpose: ["relax", "health"],
    body: "light", aroma: "subtle", time: ["evening"], effort: "easy", level: "beginner",
    effect: "은은한 단향과 무카페인. 눈의 피로와 열감을 내리는 데 전통적으로 쓰임.",
    brew: "90°C 물, 꽃 4~5송이, 3분",
    options: [{ weight: "30g", price: 15000 }, { weight: "60g", price: 25000 }],
    story: "조선시대부터 선비들이 즐겨 마신 대표적인 화차로, 국화 향이 그대로 우러납니다." },
  { id: "yuja", name: "유자차", origin: "국내 · 전남 고흥", group: "domestic", category: "과일청차",
    images: ["Korean tea-Yujacha-02.jpg", "Korean tea-Yujacha-05.jpg"],
    taste: ["sweet", "tangy"], caffeine: "free", purpose: ["health", "gift"],
    body: "medium", aroma: "bold", time: ["afternoon", "evening"], effort: "easy", level: "beginner",
    effect: "비타민C가 풍부한 유자청을 끓는 물에 타 마시는 형태. 환절기 목 관리용으로 인기.",
    brew: "뜨거운 물 200ml + 유자청 2스푼",
    options: [{ weight: "500g", price: 12000 }, { weight: "1kg", price: 18000 }],
    story: "겨울 선물세트로 가장 많이 팔리는 국내 전통 음청류 중 하나." },
  { id: "chamomile", name: "캐모마일", origin: "해외 · 이집트", group: "overseas", category: "허브차",
    images: ["Loose_chamomile_tea.jpg"],
    taste: ["floral", "sweet"], caffeine: "free", purpose: ["relax"],
    body: "light", aroma: "subtle", time: ["evening"], effort: "easy", level: "beginner",
    effect: "사과 같은 은은한 단향. 잠들기 전 마시는 허브차로 가장 널리 알려짐.",
    brew: "95°C 물, 꽃 2g, 4분",
    options: [{ weight: "20티백", price: 10000 }, { weight: "40티백", price: 18000 }],
    story: "유럽에서 수백 년간 '잠들기 전 한 잔'으로 자리잡은 대표 허브차." },
  { id: "peppermint", name: "페퍼민트", origin: "해외 · 모로코", group: "overseas", category: "허브차",
    images: ["Peppermint-tea_hg.jpg", "Tunisia-09-mint tea (6493856887).jpg"],
    taste: ["tangy"], caffeine: "free", purpose: ["digest"],
    body: "light", aroma: "bold", time: ["afternoon", "evening"], effort: "easy", level: "beginner",
    effect: "시원한 멘톨 향이 소화를 돕고 속을 편하게 함. 식후 차로 적합.",
    brew: "95°C 물, 잎 2g, 3분",
    options: [{ weight: "20티백", price: 9000 }, { weight: "40티백", price: 15000 }],
    story: "모로코 민트티 문화의 기본이 되는 허브로, 전 세계 식후 차 문화의 스테디셀러." },
  { id: "rooibos", name: "루이보스", origin: "해외 · 남아프리카공화국", group: "overseas", category: "허브차",
    images: ["Rooibos_tea_in_a_glass_with_dry_rooibos.jpg", "Rooibos_tea_2.jpg"],
    taste: ["sweet", "savory"], caffeine: "free", purpose: ["health"],
    body: "medium", aroma: "subtle", time: ["evening"], effort: "easy", level: "beginner",
    effect: "카페인 없이도 은은한 단맛. 항산화 성분이 풍부해 다이어트·컨디션 관리용으로 인기.",
    brew: "100°C 물, 찻잎 3g, 5분(오래 우려도 안 떫음)",
    options: [{ weight: "100g", price: 13000 }, { weight: "200g", price: 20000 }],
    story: "남아공 세더버그 지역에서만 자라는 관목으로, 오래 끓여도 떫지 않은 몇 안 되는 차." },
  { id: "gyeolmyeongja", name: "결명자차", origin: "국내 · 충남 태안", group: "domestic", category: "약차",
    images: [],
    taste: ["savory"], caffeine: "free", purpose: ["health", "relax"],
    body: "medium", aroma: "clear", time: ["afternoon", "evening"], effort: "standard", level: "beginner",
    effect: "구수한 볶은 맛. 예로부터 눈 건강과 이뇨 작용에 좋다고 알려진 전통 약차.",
    brew: "물 1L에 결명자 15g, 10분 끓이기",
    options: [{ weight: "200g", price: 8000 }, { weight: "500g", price: 13000 }],
    story: "보리차만큼 대중적이었던 국내 가정 상비차로, 최근 재조명되는 전통 약차 중 하나." },
  { id: "jasmine", name: "자스민 화차", origin: "국내 재가공 · 중국 푸젠성 원료", group: "domestic", category: "화차",
    images: ["Jasmine_tea.jpg", "Jasmine_Flower_Tea.jpg"],
    taste: ["floral"], caffeine: "any", purpose: ["relax", "gift"],
    body: "light", aroma: "bold", time: ["afternoon"], effort: "standard", level: "beginner",
    effect: "녹차에 자스민 꽃향을 입힌 차. 가볍고 산뜻해 식사 자리에 두루 잘 어울림.",
    brew: "85°C 물, 찻잎 3g, 2분",
    options: [{ weight: "50g", price: 15000 }, { weight: "100g", price: 25000 }],
    story: "녹차 위에 자스민 꽃을 여러 번 덮어 향을 입히는 전통 훈화 공법으로 만들어집니다." },
  { id: "boricha", name: "볶은 보리차", origin: "국내 · 전북 군산", group: "domestic", category: "약차",
    images: ["Boricha (barley tea).jpg", "Boricha (barley tea) (cropped).jpg"],
    taste: ["savory"], caffeine: "free", purpose: ["digest", "health"],
    body: "light", aroma: "clear", time: ["morning", "afternoon", "evening"], effort: "easy", level: "beginner",
    effect: "볶은 보리를 끓여 마시는 무카페인 상비차. 물 대신 하루 종일 마셔도 부담이 없다.",
    brew: "물 1L에 보리 15g, 10분 끓인 뒤 건지기",
    options: [{ weight: "300g", price: 6000 }, { weight: "1kg", price: 15000 }],
    story: "한국 가정의 냉장고에 가장 흔하게 들어 있는 차. 여름엔 차게, 겨울엔 따뜻하게 마십니다." },
  { id: "daechucha", name: "대추차", origin: "국내 · 경북 경산", group: "domestic", category: "과일청차",
    images: ["Korean.tea-Daechucha-01.jpg"],
    taste: ["sweet"], caffeine: "free", purpose: ["relax", "health"],
    body: "full", aroma: "clear", time: ["evening"], effort: "easy", level: "beginner",
    effect: "대추를 오래 고아 만든 걸쭉한 단맛. 몸을 데우는 데 전통적으로 쓰여 잠들기 전에 마시기 좋다.",
    brew: "뜨거운 물 200ml + 대추고 2스푼",
    options: [{ weight: "500g", price: 14000 }, { weight: "1kg", price: 22000 }],
    story: "잣을 몇 알 띄워 내는 것이 전통 방식으로, 예부터 손님을 맞을 때 내던 차입니다." },
  { id: "saenggangcha", name: "생강차", origin: "국내 · 전북 완주", group: "domestic", category: "과일청차",
    images: ["Saenggang-cheong.jpg"],
    taste: ["sweet", "tangy"], caffeine: "free", purpose: ["health", "relax"],
    body: "full", aroma: "bold", time: ["evening"], effort: "easy", level: "beginner",
    effect: "알싸한 매운맛과 단맛이 함께 온다. 목이 칼칼한 환절기에 특히 많이 찾는 차.",
    brew: "뜨거운 물 200ml + 생강청 2스푼",
    options: [{ weight: "500g", price: 13000 }, { weight: "1kg", price: 20000 }],
    story: "완주 봉동 생강은 조선시대 진상품으로 오르던 국내 대표 생강 산지입니다." },
  { id: "ssanghwacha", name: "쌍화차", origin: "국내 · 전남 장성", group: "domestic", category: "약차",
    images: ["Ssanghwacha.jpg"],
    taste: ["savory"], caffeine: "free", purpose: ["health", "relax"],
    body: "full", aroma: "bold", time: ["evening"], effort: "ritual", level: "intermediate",
    effect: "여러 약재를 함께 달인 전통 보양차. 진하고 묵직해 호불호가 뚜렷하게 갈린다.",
    brew: "약재 팩 1개를 물 1L에 넣고 30분 이상 달이기",
    options: [{ weight: "20팩", price: 18000 }, { weight: "40팩", price: 32000 }],
    story: "옛 다방의 상징 같은 차로, 노른자를 띄워 내던 시절의 기억이 그대로 남아 있습니다." },
  { id: "yeonkkotcha", name: "연꽃차", origin: "국내 · 전남 무안", group: "domestic", category: "화차",
    images: ["Yeonkkot-cha 2.jpg"],
    taste: ["floral"], caffeine: "free", purpose: ["relax", "gift"],
    body: "light", aroma: "subtle", time: ["evening"], effort: "standard", level: "intermediate",
    effect: "연꽃 봉오리를 통째로 말려 우리는 차. 뜨거운 물에서 꽃잎이 다시 벌어진다.",
    brew: "90°C 물, 꽃 1송이, 5분",
    options: [{ weight: "5송이", price: 22000 }, { weight: "10송이", price: 40000 }],
    story: "무안 일대 연밭에서 새벽에 딴 봉오리만 씁니다. 모양 때문에 선물용으로 자주 찾습니다." },
  { id: "sencha", name: "시즈오카 센차", origin: "해외 · 일본 시즈오카", group: "overseas", category: "녹차",
    images: ["Sencha Japanischer Grüner Tee.jpg", "Green tea leaves.jpg"],
    taste: ["astringent", "savory"], caffeine: "need", purpose: ["focus", "digest"],
    body: "medium", aroma: "clear", time: ["morning", "afternoon"], effort: "standard", level: "beginner",
    effect: "일본 녹차 생산량의 대부분을 차지하는 기본 녹차. 감칠맛과 산뜻한 떫은맛이 균형을 이룬다.",
    brew: "70°C 물, 찻잎 4g, 1분",
    options: [{ weight: "100g", price: 18000 }, { weight: "200g", price: 30000 }],
    story: "시즈오카는 일본 차 생산의 중심지로, 후지산 자락의 큰 일교차가 잎을 두텁게 만듭니다." },
  { id: "matcha", name: "우지 말차", origin: "해외 · 일본 교토 우지", group: "overseas", category: "말차",
    images: ["Matcha layout with leaf, tea, and powder.jpg", "Matcha tea.jpg"],
    taste: ["savory", "astringent"], caffeine: "need", purpose: ["focus", "gift"],
    body: "full", aroma: "bold", time: ["morning", "afternoon"], effort: "ritual", level: "advanced",
    effect: "찻잎을 통째로 갈아 마시는 가루차. 우린 물만 마시는 차와 달리 잎 전체를 섭취한다.",
    brew: "80°C 물 70ml, 말차 2g, 차선으로 거품 내기",
    options: [{ weight: "30g", price: 28000 }, { weight: "100g", price: 75000 }],
    story: "우지는 800년 넘게 말차를 만들어 온 산지로, 그늘막 재배로 떫은맛을 낮춥니다." },
  { id: "longjing", name: "시후 룽징(용정차)", origin: "해외 · 중국 항저우", group: "overseas", category: "녹차",
    images: ["Longjing tea.jpg", "Dragon Well Tea Plantation, Hangzhou (3020076220).jpg"],
    taste: ["savory", "sweet"], caffeine: "need", purpose: ["focus", "gift"],
    body: "light", aroma: "clear", time: ["morning", "afternoon"], effort: "standard", level: "intermediate",
    effect: "솥에 덖어 납작하게 편 잎. 볶은 콩 같은 고소함과 맑은 단맛이 특징이다.",
    brew: "80°C 물, 찻잎 3g, 2분",
    options: [{ weight: "50g", price: 35000 }, { weight: "100g", price: 62000 }],
    story: "항저우 서호 주변에서만 나는 차로, 중국 10대 명차 가운데 가장 널리 알려져 있습니다." },
  { id: "tieguanyin", name: "안시 철관음", origin: "해외 · 중국 푸젠성", group: "overseas", category: "우롱차",
    images: ["Tieguanyin2.jpg", "Oolong tea leaf.jpg"],
    taste: ["floral", "sweet"], caffeine: "need", purpose: ["relax", "gift"],
    body: "medium", aroma: "bold", time: ["afternoon"], effort: "ritual", level: "intermediate",
    effect: "난꽃 향이 뚜렷한 반발효차. 여러 번 우려도 향이 쉽게 무너지지 않는다.",
    brew: "95°C 물, 찻잎 5g, 30초씩 여러 번",
    options: [{ weight: "50g", price: 26000 }, { weight: "100g", price: 45000 }],
    story: "관음보살이 점지했다는 전설에서 이름이 왔습니다. 우롱차 입문자에게 가장 많이 권해지는 차입니다." },
  { id: "assam", name: "아쌈 홍차", origin: "해외 · 인도 아쌈", group: "overseas", category: "홍차",
    images: ["Assam black tea.jpg", "Tea, two leaves and a bud.jpg"],
    taste: ["astringent", "savory"], caffeine: "need", purpose: ["focus"],
    body: "full", aroma: "clear", time: ["morning"], effort: "standard", level: "beginner",
    effect: "맥아 같은 진한 단맛과 묵직한 바디감. 우유를 넣는 밀크티 베이스로 가장 널리 쓰인다.",
    brew: "100°C 물, 찻잎 3g, 4분",
    options: [{ weight: "100g", price: 14000 }, { weight: "200g", price: 24000 }],
    story: "브라마푸트라 강 유역의 더운 저지대에서 자라며, 세계 홍차 생산량의 큰 몫을 차지합니다." },
  { id: "hibiscus", name: "히비스커스", origin: "해외 · 이집트", group: "overseas", category: "허브차",
    images: ["Hibiscus tea.jpg", "A glass of hibiscus tea 01.jpg"],
    taste: ["tangy"], caffeine: "free", purpose: ["health", "digest"],
    body: "medium", aroma: "bold", time: ["afternoon"], effort: "easy", level: "beginner",
    effect: "새콤한 산미와 선명한 붉은빛. 차갑게 우리면 청량감이 크게 살아난다.",
    brew: "95°C 물, 꽃받침 2g, 5분 (냉침도 가능)",
    options: [{ weight: "20티백", price: 11000 }, { weight: "40티백", price: 19000 }],
    story: "이집트에서는 카르카데라 부르며, 결혼식과 손님 접대 자리에 빠지지 않는 음료입니다." },
];
// 차 도구 — 맛 관련 속성이 없어 취향 큐레이터 채점에서는 제외된다
const TOOLS = [
  { id: "gaiwan", name: "청자 개완", origin: "중국식 우림 그릇", group: "tool", category: "다관",
    images: ["Chinese tea set and three gaiwan (cropped).jpg"],
    material: "자기", capacity: "120ml",
    effect: "뚜껑으로 찻잎을 막아 따르는 우림 그릇. 향이 강한 차의 향을 가장 잘 살립니다.",
    usage: "찻잎을 넣고 물을 부은 뒤 뚜껑을 살짝 기울여 따릅니다. 잎 상태를 눈으로 확인하며 우릴 수 있습니다.",
    options: [{ weight: "1개", price: 38000 }],
    story: "명나라 때 자리 잡은 형태로, 다관보다 씻기 쉬워 여러 차를 번갈아 마시기에 좋습니다." },
  { id: "jasaho", name: "자사호 다관", origin: "중국 이싱", group: "tool", category: "다관",
    images: ["Yixing clay teapot.jpg", "Teapot (Yixing ware, about 1900).JPG"],
    material: "자사토 (무유약)", capacity: "200ml",
    effect: "쓸수록 차향이 배어 길이 드는 다관. 보이차·우롱차처럼 진한 차에 어울립니다.",
    usage: "한 다관에 한 종류의 차만 쓰는 것이 원칙입니다. 세제 없이 뜨거운 물로만 헹굽니다.",
    options: [{ weight: "1개", price: 95000 }],
    story: "이싱의 자사토는 미세한 기공이 있어 차의 향을 머금는다고 알려져 있습니다." },
  { id: "celadon-cup", name: "고려청자 찻잔", origin: "국내 · 전남 강진", group: "tool", category: "찻잔",
    images: ["Cup and stand from Korea, late 12th century, stoneware with celadon glaze, HAA.JPG"],
    material: "청자", capacity: "80ml",
    effect: "얇은 잔벽이 차의 온도를 빠르게 전합니다. 녹차·황차처럼 섬세한 차에 어울립니다.",
    usage: "잔 받침과 한 벌로 씁니다. 첫 사용 전 미지근한 물에 한 번 헹궈 주세요.",
    options: [{ weight: "1개", price: 42000 }, { weight: "2개 세트", price: 78000 }],
    story: "고려 비색 청자의 형태를 강진 가마에서 재현한 잔입니다." },
  { id: "buncheong-bowl", name: "분청사기 찻사발", origin: "국내 · 경남 김해", group: "tool", category: "찻잔",
    images: ["Tea bowl, Korea, Joseon dynasty, 16th century AD, Mishima-hakeme type, buncheong ware, stoneware with white engobe and translucent, greenish-gray glaze, gold lacquer - Ethnological Museum, Berlin - DSC02061.JPG"],
    material: "분청사기", capacity: "300ml",
    effect: "말차를 격불해 마시는 넓은 사발. 두 손으로 감싸 쥐는 크기입니다.",
    usage: "말차 2g에 80°C 물 70ml를 붓고 차선으로 저어 거품을 냅니다.",
    options: [{ weight: "1개", price: 68000 }],
    story: "조선 분청의 자유로운 붓질은 일본 다도에서 특히 귀하게 여겨졌습니다." },
  { id: "strainer", name: "스테인리스 차거름망", origin: "우림 보조 도구", group: "tool", category: "우림 도구",
    images: ["Teacup&Strainer.JPG"],
    material: "스테인리스 스틸", capacity: "잔 지름 7~9cm",
    effect: "잔이나 다관 위에 올려 찻잎을 걸러냅니다. 매일 쓰기에 가장 무난한 도구입니다.",
    usage: "잔 위에 올리고 우린 차를 부으면 됩니다. 쓴 뒤 바로 헹궈 말려 주세요.",
    options: [{ weight: "1개", price: 12000 }],
    story: "도구를 하나만 들인다면 대부분의 차인이 거름망부터 권합니다." },
  { id: "chasi", name: "대나무 차시", origin: "우림 보조 도구", group: "tool", category: "우림 도구",
    images: ["Matcha Scoop.jpg"],
    material: "대나무", capacity: "1스푼 약 2g",
    effect: "말차나 찻잎을 덜어내는 숟가락. 금속 냄새가 배지 않습니다.",
    usage: "말차 한 잔에 두 번 뜨는 양이 기준입니다. 물에 담그지 말고 마른 천으로 닦습니다.",
    options: [{ weight: "1개", price: 9000 }],
    story: "대나무 마디를 그대로 살려 깎기 때문에 같은 모양이 하나도 없습니다." },
  { id: "china-set", name: "중국 다기 세트", origin: "중국식 구성", group: "tool", category: "다기 세트",
    images: ["Chinese Tea Ceremony.jpg"],
    material: "자기", capacity: "다관 180ml + 잔 4개",
    effect: "다관·숙우·잔이 한 벌로 구성된 기본 세트. 처음 다구를 갖출 때 적합합니다.",
    usage: "다관에서 우린 차를 숙우에 옮긴 뒤 잔에 나눠 따릅니다. 농도가 고르게 맞춰집니다.",
    options: [{ weight: "1세트", price: 128000 }],
    story: "여러 번 나눠 우리는 중국식 우림법에 맞춰 잔이 작게 구성됩니다." },
  { id: "darye-set", name: "다례 소반 다기 세트", origin: "국내 · 한국식 구성", group: "tool", category: "다기 세트",
    images: ["Korean tea ceremony-Darye-01.jpg"],
    material: "백자 + 소반", capacity: "다관 250ml + 잔 2개",
    effect: "소반 위에 다관과 잔을 올려 쓰는 한국식 구성. 손님을 맞는 자리에 씁니다.",
    usage: "소반째 상에 올려 내고, 다관에서 잔으로 직접 따릅니다.",
    options: [{ weight: "1세트", price: 165000 }],
    story: "다례(茶禮)는 차를 내는 예를 뜻합니다. 이 세트는 그 자리를 그대로 옮겨 온 구성입니다." },
];

// 샵·검색이 다루는 전체 품목 (차 + 도구)
const PRODUCTS = TEAS.concat(TOOLS);

// 샵 대분류
const GROUPS = [
  { id: "domestic", label: "국내차", icon: "🍵" },
  { id: "overseas", label: "해외차", icon: "🌏" },
  { id: "tool",     label: "차 도구", icon: "🫖" },
];


// 커뮤니티 피드 — 다례 팀이 직접 작성하는 콘텐츠 (팀 계정 발행 전 초안.
// 좋아요/댓글/스크랩 수는 배포 시 0에서 시작하며 가짜 반응은 넣지 않는다)
const FEED_POSTS = [
  { id: "post-caffeine-guide", category: "녹차", date: "2026.09.05", readMin: 4,
    image: "Dried_jakseol_green_tea_leaves.jpg",
    title: "카페인 예민한데 녹차 좋아한다면? 우전과 세작의 차이",
    summary: "같은 녹차인데 왜 어떤 건 잠이 안 오고 어떤 건 괜찮을까요. 첫물차와 늦물차의 카테킨 함량 차이부터 우리는 물 온도까지, 카페인 부담을 줄이는 우리기 팁을 정리했습니다." },
  { id: "post-puer-myth", category: "발효차", date: "2026.09.03", readMin: 6,
    image: "Pu-erh_tea.JPG",
    title: "보이차는 다 똑같지 않습니다 — 생차 vs 숙차 완전 정리",
    summary: "보이차 하나로 뭉뚱그려 부르지만 발효 방식에 따라 맛과 효능이 완전히 다릅니다. 처음 보이차를 접하는 분들이 가장 많이 헷갈리는 지점을 짧게 짚어드려요." },
  { id: "post-herbal-sleep", category: "허브차", date: "2026.09.01", readMin: 3,
    image: "Loose_chamomile_tea.jpg",
    title: "잠들기 전 한 잔, 캐모마일 말고도 있습니다",
    summary: "캐모마일이 대표적이지만 취향에 안 맞을 수도 있어요. 무카페인이면서 이완에 도움을 주는 허브차 3종을 향과 맛 기준으로 비교했습니다." },
  { id: "post-darjeeling-flush", category: "홍차", date: "2026.08.28", readMin: 5,
    image: "Darjeeling-tea-first-flush-in-cup.jpg",
    title: "퍼스트 플러시가 비싼 이유, 한 번은 마셔볼 가치가 있을까",
    summary: "봄 첫 수확분이라는 이유만으로 가격이 두 배가 됩니다. 세컨드 플러시와 나란히 우려 마셔보고 향·바디감·가격을 기준으로 솔직하게 정리했습니다." },
  { id: "post-yuja-winter", category: "과일청차", date: "2026.08.25", readMin: 3,
    image: "Korean tea-Yujacha-02.jpg",
    title: "환절기 목 관리, 유자차는 몇 스푼이 적당할까",
    summary: "유자청은 설탕 비율이 높아 무작정 진하게 타면 단맛만 남습니다. 물 온도와 스푼 수를 바꿔가며 가장 균형 잡힌 비율을 찾아봤습니다." },
  { id: "post-flower-tea", category: "화차", date: "2026.08.21", readMin: 4,
    image: "Jasmine_Flower_Tea.jpg",
    title: "향으로 마시는 차, 화차 입문 가이드",
    summary: "자스민·국화처럼 꽃향을 입힌 차는 첫인상이 강해 호불호가 갈립니다. 처음 마신다면 어떤 순서로 접근하면 좋은지 정리했습니다." },
  { id: "post-oolong-range", category: "우롱차", date: "2026.08.18", readMin: 5,
    image: "Oolong_tea_leaf.jpg",
    title: "우롱차는 녹차와 홍차 사이 어디쯤에 있을까",
    summary: "산화도에 따라 같은 우롱차도 녹차에 가깝기도, 홍차에 가깝기도 합니다. 산화도별로 맛이 어떻게 달라지는지 지도처럼 그려봤습니다." },
  { id: "post-boseong-field", category: "녹차", date: "2026.08.14", readMin: 7,
    image: "Boseong_banner_Green_Tea_Plantation.jpg",
    title: "보성 다원에 다녀왔습니다 — 계단식 차밭이 만드는 맛",
    summary: "같은 품종이라도 경사와 해무에 따라 잎이 달라집니다. 산지에서 직접 보고 들은 재배 방식이 우리 잔에 어떻게 도착하는지 이야기합니다." },
];
