// 다례(茶禮) 취향 큐레이터 데이터셋 — tea-mvp-reference.html에서 그대로 이식
const TASTE_OPTS = [
  { id: "astringent", label: "떫은맛" },
  { id: "sweet", label: "단맛" },
  { id: "savory", label: "구수함" },
  { id: "tangy", label: "산미·상큼함" },
  { id: "floral", label: "꽃·향긋함" },
];

const CAFFEINE_OPTS = [
  { id: "need", label: "카페인 필요해요" },
  { id: "free", label: "무카페인 선호" },
  { id: "any", label: "상관없어요" },
];

const PURPOSE_OPTS = [
  { id: "relax", label: "이완·휴식" },
  { id: "focus", label: "집중·각성" },
  { id: "digest", label: "소화·속편함" },
  { id: "health", label: "건강관리·다이어트" },
  { id: "gift", label: "선물·특별한 날" },
];

const TEAS = [
  { id: "hadong-ujeon", name: "하동 우전 녹차", origin: "국내 · 경남 하동", category: "녹차",
    taste: ["savory", "sweet"], caffeine: "need", purpose: ["focus", "gift"],
    effect: "떫지 않고 감칠맛이 강한 첫물차. 카테킨이 풍부해 각성·항산화에 도움.",
    brew: "70°C 물, 찻잎 3g, 1분 30초", price: "2.5만~4만원 (50g)",
    story: "곡우 전 딴 첫잎만 쓰는 하동의 대표 전통 녹차. 국내 녹차 산지 중 재배 역사가 가장 깁니다." },
  { id: "boseong-sejak", name: "보성 세작 녹차", origin: "국내 · 전남 보성", category: "녹차",
    taste: ["astringent", "savory"], caffeine: "need", purpose: ["focus"],
    effect: "우전보다 진한 떫은맛과 개운한 뒷맛. 식사 후 입가심에 좋음.",
    brew: "75°C 물, 찻잎 3g, 1분", price: "1.5만~2.5만원 (100g)",
    story: "보성 다원의 계단식 차밭에서 자란 잎으로 만든, 가장 대중적인 국산 녹차." },
  { id: "hadong-hwangcha", name: "하동 황차", origin: "국내 · 경남 하동", category: "발효차",
    taste: ["sweet", "savory"], caffeine: "need", purpose: ["digest", "relax"],
    effect: "약발효로 떫은맛을 낮추고 단맛을 살린 차. 위에 부담이 적어 공복에도 무난.",
    brew: "85°C 물, 찻잎 3g, 2분", price: "2만~3만원 (50g)",
    story: "녹차보다 산화를 더 진행시켜 구수함을 끌어올린 한국 고유의 발효 방식." },
  { id: "yunnan-puer", name: "윈난 보이차(숙차)", origin: "해외 · 중국 윈난성", category: "발효차",
    taste: ["savory"], caffeine: "need", purpose: ["digest", "health"],
    effect: "후발효차 특유의 흙내와 구수함. 기름진 음식 후 소화를 돕는다고 알려짐.",
    brew: "95°C 물, 찻잎 5g, 세차 후 20~30초씩 여러 번", price: "3만~8만원 (병차 100g)",
    story: "윈난 대엽종을 눌러 저장·후발효시킨 차. 오래 묵힐수록 맛이 부드러워집니다." },
  { id: "taiwan-oolong", name: "대만 동방미인 우롱차", origin: "해외 · 대만 신주", category: "우롱차",
    taste: ["floral", "sweet"], caffeine: "any", purpose: ["gift", "relax"],
    effect: "진딧물이 문 잎으로 만들어 과일·꿀 향이 강한 고급 반발효차.",
    brew: "90°C 물, 찻잎 4g, 1분", price: "4만~7만원 (50g)",
    story: "벌레가 갉아먹은 잎이 오히려 특유의 향을 만든다는, 우연에서 시작된 명차." },
  { id: "darjeeling", name: "다르질링 홍차(퍼스트 플러시)", origin: "해외 · 인도 다르질링", category: "홍차",
    taste: ["tangy", "astringent"], caffeine: "need", purpose: ["focus"],
    effect: "머스캣 포도 향과 산뜻한 산미. '홍차의 샴페인'으로 불림.",
    brew: "90°C 물, 찻잎 3g, 3분", price: "2만~4만원 (50g)",
    story: "봄 첫 수확분만 이렇게 불리며, 세계 홍차 경매가에서 가장 높은 값에 거래됩니다." },
  { id: "breakfast-blend", name: "잉글리시 브렉퍼스트 블렌드", origin: "해외 · 인도·스리랑카 블렌드", category: "홍차",
    taste: ["astringent", "sweet"], caffeine: "need", purpose: ["focus"],
    effect: "진하고 묵직한 바디감. 우유·설탕과 잘 어울려 아침 각성용으로 적합.",
    brew: "100°C 물, 찻잎 3g, 3~4분", price: "1.2만~2만원 (100g)",
    story: "아삼과 실론 찻잎을 배합해 진한 맛을 표준화한, 가장 널리 소비되는 홍차 블렌드." },
  { id: "chrysanthemum", name: "국화차", origin: "국내 · 전북 정읍", category: "화차",
    taste: ["floral", "sweet"], caffeine: "free", purpose: ["relax", "health"],
    effect: "은은한 단향과 무카페인. 눈의 피로와 열감을 내리는 데 전통적으로 쓰임.",
    brew: "90°C 물, 꽃 4~5송이, 3분", price: "1.5만~2.5만원 (30g)",
    story: "조선시대부터 선비들이 즐겨 마신 대표적인 화차로, 국화 향이 그대로 우러납니다." },
  { id: "yuja", name: "유자차", origin: "국내 · 전남 고흥", category: "과일청차",
    taste: ["sweet", "tangy"], caffeine: "free", purpose: ["health", "gift"],
    effect: "비타민C가 풍부한 유자청을 끓는 물에 타 마시는 형태. 환절기 목 관리용으로 인기.",
    brew: "뜨거운 물 200ml + 유자청 2스푼", price: "1.2만~1.8만원 (500g)",
    story: "겨울 선물세트로 가장 많이 팔리는 국내 전통 음청류 중 하나." },
  { id: "chamomile", name: "캐모마일", origin: "해외 · 이집트", category: "허브차",
    taste: ["floral", "sweet"], caffeine: "free", purpose: ["relax"],
    effect: "사과 같은 은은한 단향. 잠들기 전 마시는 허브차로 가장 널리 알려짐.",
    brew: "95°C 물, 꽃 2g, 4분", price: "1만~1.8만원 (20티백)",
    story: "유럽에서 수백 년간 '잠들기 전 한 잔'으로 자리잡은 대표 허브차." },
  { id: "peppermint", name: "페퍼민트", origin: "해외 · 모로코", category: "허브차",
    taste: ["tangy"], caffeine: "free", purpose: ["digest"],
    effect: "시원한 멘톨 향이 소화를 돕고 속을 편하게 함. 식후 차로 적합.",
    brew: "95°C 물, 잎 2g, 3분", price: "9천~1.5만원 (20티백)",
    story: "모로코 민트티 문화의 기본이 되는 허브로, 전 세계 식후 차 문화의 스테디셀러." },
  { id: "rooibos", name: "루이보스", origin: "해외 · 남아프리카공화국", category: "허브차",
    taste: ["sweet", "savory"], caffeine: "free", purpose: ["health"],
    effect: "카페인 없이도 은은한 단맛. 항산화 성분이 풍부해 다이어트·컨디션 관리용으로 인기.",
    brew: "100°C 물, 찻잎 3g, 5분(오래 우려도 안 떫음)", price: "1.3만~2만원 (100g)",
    story: "남아공 세더버그 지역에서만 자라는 관목으로, 오래 끓여도 떫지 않은 몇 안 되는 차." },
  { id: "gyeolmyeongja", name: "결명자차", origin: "국내 · 충남 태안", category: "허브차",
    taste: ["savory"], caffeine: "free", purpose: ["health", "relax"],
    effect: "구수한 볶은 맛. 예로부터 눈 건강과 이뇨 작용에 좋다고 알려진 전통 약차.",
    brew: "물 1L에 결명자 15g, 10분 끓이기", price: "8천~1.3만원 (200g)",
    story: "보리차만큼 대중적이었던 국내 가정 상비차로, 최근 재조명되는 전통 약차 중 하나." },
  { id: "jasmine", name: "자스민 화차", origin: "국내 재가공 · 중국 푸젠성 원료", category: "화차",
    taste: ["floral"], caffeine: "any", purpose: ["relax", "gift"],
    effect: "녹차에 자스민 꽃향을 입힌 차. 가볍고 산뜻해 식사 자리에 두루 잘 어울림.",
    brew: "85°C 물, 찻잎 3g, 2분", price: "1.5만~2.5만원 (50g)",
    story: "녹차 위에 자스민 꽃을 여러 번 덮어 향을 입히는 전통 훈화 공법으로 만들어집니다." },
];

// 커뮤니티 피드 — 다례 팀이 직접 작성하는 콘텐츠 (팀 계정 발행 전 초안. 좋아요/댓글/스크랩 수는 배포 시 0에서 시작)
const FEED_POSTS = [
  { id: "post-caffeine-guide", category: "녹차",
    title: "카페인 예민한데 녹차 좋아한다면? 우전과 세작의 차이",
    summary: "같은 녹차인데 왜 어떤 건 잠이 안 오고 어떤 건 괜찮을까요. 첫물차와 늦물차의 카테킨 함량 차이부터 우리는 물 온도까지, 카페인 부담을 줄이는 우리기 팁을 정리했습니다.",
    date: "2026.09.05" },
  { id: "post-puer-myth", category: "발효차",
    title: "보이차는 다 똑같지 않습니다 — 생차 vs 숙차 완전 정리",
    summary: "보이차 하나로 뭉뚱그려 부르지만 발효 방식에 따라 맛과 효능이 완전히 다릅니다. 처음 보이차를 접하는 분들이 가장 많이 헷갈리는 지점을 짧게 짚어드려요.",
    date: "2026.09.03" },
  { id: "post-herbal-sleep", category: "허브차",
    title: "잠들기 전 한 잔, 캐모마일 말고도 있습니다",
    summary: "캐모마일이 대표적이지만 취향에 안 맞을 수도 있어요. 무카페인이면서 이완에 도움을 주는 허브차 3종을 향과 맛 기준으로 비교했습니다.",
    date: "2026.09.01" },
];
